# Generated by Django 3.2.3 on 2021-05-28 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ourwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='work')),
                ('date', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Ourworks',
                'ordering': ['date'],
            },
        ),
    ]
