# Generated by Django 3.2.3 on 2021-05-28 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('desc', models.TextField(blank=True)),
                ('img', models.ImageField(upload_to='blog')),
                ('author', models.CharField(default=None, max_length=100)),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Blogs',
                'ordering': ('-date',),
            },
        ),
    ]
